name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  gh_token:  # id of input
    description: 'GitHub Token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node18'
  main: 'dist/index.js'
