name: 'Automatic tagging'
description: 'Automatic installation of tags according to Gitflow'
inputs:
  gh_token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
